name = "min_night"
license = "MIT"
licenselink = "https://github.com/nathancday/min_night/blob/master/LICENSE.md"
description = "An easy on the eyes blog theme with night-mode."
homepage = "http://github.com/nathancday/min_night"
tags = ["blog", "night-mode"]
features = ["twitter-cards"]
min_version = "0.35"

[author]
  name = "Nate Day"
  homepage = "https://natedayta.com"
  
[original]
  author = "Calin Tataru"
  homepage = "https://calintat.github.io/"
  repo = "https://github.com/calintat/minimal"
