#!/usr/bin/python3
import sys
import argparse


def print_banner():
    print('''
         ____    _____ _   _ ____________   __  ____  _____    _    ____  
         \ \ \  |  ___| | | |__  /__  /\ \ / / | __ )| ____|  / \  |  _ \ 
          \ \ \ | |_  | | | | / /  / /  \ V /  |  _ \|  _|   / _ \ | |_) |
          / / / |  _| | |_| |/ /_ / /_   | |   | |_) | |___ / ___ \|  _ < 
         /_/_/  |_|    \___//____/____|  |_|   |____/|_____/_/   \_\_| \_\
    
    ''')


print_banner()
if (len(sys.argv) == 1):
    
    print(f'''
        usage :: {sys.argv[0]} <file> [options]
    ''')

# TODO :: indent this
parser = argparse.ArgumentParser()
parser.add_argument('-L', '--lol',
                    dest = 'lol',
                    action='store_true',
                    help = 'we don\'t have any args yet'
                    )

args = parser.parse_args()
