#!/usr/bin/python3

'''
:::::::::::: Driver For Tests ::::::::::::

    ► Stuff & things 

'''

# import outter path to expose core
import csv
from pathlib import Path
import sys
# sys.path.append('../')

from fuzzybear import Harness
import argparse
from pathlib import Path

## CSV TESTS ##
from fuzzybear.strategies import CSV

## ELF Test ##
from fuzzybear.strategies import ELF

## JPEG Test ##
from fuzzybear.strategies import JPEG

## JSON Test ##
# from fuzzybear.strategies import JSON 

## PDF Test ##
from fuzzybear.strategies import PDF

## TXT Test ##
from fuzzybear.strategies import TXT

## XML Test ##
from fuzzybear.strategies import XML

## ADD TEST IMPORT ## ^



def print_banner():
    print('''
          ____    _____ _____ ____ _____   _____ _   _ ____________   __
          \ \ \  |_   _| ____/ ___|_   _| |  ___| | | |__  /__  /\ \ / /
           \ \ \   | | |  _| \___ \ | |   | |_  | | | | / /  / /  \ V / 
           / / /   | | | |___ ___) || |   |  _| | |_| |/ /_ / /_   | |  
          /_/_/    |_| |_____|____/ |_|   |_|    \___//____/____|  |_|  
                                                              
          ____  _____    _    ____  
         | __ )| ____|  / \  |  _ \ 
         |  _ \|  _|   / _ \ | |_) |
         | |_) | |___ / ___ \|  _ < 
         |____/|_____/_/   \_\_| \_\
                           
    ''')


########################## :: [DEFINE TESTS] :: ##########################


def test_harness():

    TEST_DIR = './tests/components/harness/'

    print(f'''
        [>>] Running tests from {TEST_DIR}
    ''')

    for file in Path(f'{TEST_DIR}/ins').glob('*'):
        input = "".join(open(file).readlines())
        for binary in Path(f'{TEST_DIR}/bins').glob('*'):
            print(f'''
                ► Trying {file.name} against {binary.name}
            ''')

            harness = Harness.Harness(binary)
            res = harness.open_pipe(input)

            print(f'''
                    [+] Response from {binary.name} was {res}
            ''')

# test csv1
def test_csv():
    TEST_DIR = './tests/complete'
    TEST_BINARY = f'{TEST_DIR}/target-bins/csv1'
    TEST_SAMPLE = f'{TEST_DIR}/target-ins/csv1.txt'

    print(f"""
        [>>] Running CSV test against {TEST_BINARY.split('/')[-1]} with {TEST_SAMPLE.split('/')[-1]}
    """)

    harness = Harness.Harness(TEST_BINARY)

    csv_worker = CSV.CSV(TEST_SAMPLE)
    
    # buf = ''
    # csv_writer = csv.writer(buf)
    for x in range(10):
        for x in csv_worker.run():
            
            # @ here would mark the place the 
            # aggregator feeds harness
            print(x)
            print(f"\nPiping to harness, res was {harness.open_pipe(x)}\n")
    



###########################################################################

print_banner()

parser = argparse.ArgumentParser()


'''
parser.add_argument('-P', '--your-test',
                    dest = 'test-name',
                    action='store_true',
                    help = 'what is your test'
                    )
'''

parser.add_argument('-H', '--harness',
                    dest = 'harness',
                    action='store_true',
                    help = 'test harness'
                    )


parser.add_argument('-CSV', '--CSV-codec',
                    dest = 'CSV',
                    action='store_true',
                    help = 'test the csv codec binaries'
                    )



## Add command line args for your test ^

args = parser.parse_args()

if (len(sys.argv) == 1): parser.print_help()

'''
:::::::::::: Call Tests ::::::::::::

 ► if (args.test): test_name()
'''

if (args.harness): test_harness()

if (args.CSV): test_csv()
